
document.addEventListener('DOMContentLoaded',()=>{
 setTimeout(()=>document.querySelector('.page-loader')?.classList.add('hidden'),250);
 document.querySelector('[data-theme-toggle]')?.addEventListener('click',toggleTheme);
 document.querySelector('[data-refresh]')?.addEventListener('click',()=>location.reload());document.querySelector('[data-scroll-top]')?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
 document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();document.getElementById('globalSearch')?.focus()}if(e.altKey&&e.key.toLowerCase()==='t')toggleTheme()});
 initGlobalSearch();initInvestmentModal();document.querySelectorAll('[data-add-investment]').forEach(b=>b.addEventListener('click',()=>bootstrap.Modal.getOrCreateInstance(document.getElementById('investmentModal')).show()));
});
function money(v,d=0){return '₹'+Number(v).toLocaleString('en-IN',{minimumFractionDigits:d,maximumFractionDigits:d})}function pct(v){return `${v>=0?'+':''}${Number(v).toFixed(2)}%`}function trendClass(v){return v>=0?'trend-up':'trend-down'}
function showToast(message){let c=document.querySelector('.toast-container');if(!c){c=document.createElement('div');c.className='toast-container position-fixed end-0 bottom-0 p-3';document.body.append(c)}const el=document.createElement('div');el.className='toast align-items-center premium-modal';el.innerHTML=`<div class="d-flex"><div class="toast-body">${message}</div><button class="btn-close me-2 m-auto" data-bs-dismiss="toast"></button></div>`;c.append(el);new bootstrap.Toast(el,{delay:2600}).show();el.addEventListener('hidden.bs.toast',()=>el.remove())}
function initGlobalSearch(){const input=document.getElementById('globalSearch'),box=document.getElementById('searchResults');if(!input||!box)return;const render=q=>{const res=FINORA_DATA.stocks.filter(s=>(s.company+' '+s.symbol).toLowerCase().includes(q.toLowerCase())).slice(0,7);box.innerHTML=q?(res.length?res.map(s=>`<a class="search-result" href="stock.html?symbol=${s.symbol}"><span class="stock-logo">${s.symbol[0]}</span><span><strong class="heading">${s.company}</strong><small class="d-block">${money(s.price,2)} · <span class="${trendClass(s.change)}">${pct(s.change)}</span></small></span><span class="search-symbol">${s.symbol}</span></a>`).join(''):'<div class="empty-state py-4"><i class="bi bi-search"></i><h6>No results found</h6></div>'):'';box.classList.toggle('show',!!q)};input.addEventListener('input',e=>render(e.target.value.trim()));input.addEventListener('focus',e=>render(e.target.value.trim()));document.addEventListener('click',e=>{if(!e.target.closest('.global-search'))box.classList.remove('show')});document.querySelector('.global-search>i')?.addEventListener('click',()=>document.querySelector('.topbar')?.classList.toggle('search-open'))}
function initInvestmentModal(){if(document.getElementById('investmentModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="modal fade" id="investmentModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content premium-modal"><div class="modal-header"><div><h5 class="modal-title">Add Investment</h5><small>Add a completed buy transaction to your portfolio</small></div><button class="btn-close" data-bs-dismiss="modal"></button></div><form id="investmentForm"><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Stock Name</label><input name="company" class="form-control premium-input" required></div><div class="col-md-6"><label class="form-label">Symbol</label><input name="symbol" class="form-control premium-input text-uppercase" required></div><div class="col-md-4"><label class="form-label">Quantity</label><input name="qty" type="number" min="1" class="form-control premium-input" required></div><div class="col-md-4"><label class="form-label">Buy Price</label><input name="price" type="number" min="0.01" step="0.01" class="form-control premium-input" required></div><div class="col-md-4"><label class="form-label">Buy Date</label><input name="date" type="date" class="form-control premium-input" required></div><div class="col-md-6"><label class="form-label">Broker</label><select name="broker" class="form-select premium-input" required><option value="">Select broker</option><option>Zerodha</option><option>Groww</option><option>ICICI Direct</option><option>Upstox</option></select></div><div class="col-md-6"><label class="form-label">Notes</label><input name="notes" class="form-control premium-input"></div></div></div><div class="modal-footer border-0"><button type="button" class="btn btn-soft" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary-pro">Add Investment</button></div></form></div></div></div>`);document.getElementById('investmentForm').addEventListener('submit',e=>{e.preventDefault();if(!e.target.checkValidity()){e.target.classList.add('was-validated');return}const fd=Object.fromEntries(new FormData(e.target));const custom=JSON.parse(localStorage.getItem('finoraInvestments')||'[]');custom.push({...fd,qty:Number(fd.qty),price:Number(fd.price),createdAt:Date.now()});localStorage.setItem('finoraInvestments',JSON.stringify(custom));bootstrap.Modal.getInstance(document.getElementById('investmentModal')).hide();e.target.reset();showToast(`${fd.symbol.toUpperCase()} added to portfolio`);document.dispatchEvent(new CustomEvent('finora:investment-added',{detail:fd}))})}
