
const cssVar=n=>getComputedStyle(document.documentElement).getPropertyValue(n).trim();
const chartText=()=>cssVar('--text');
const chartGrid=()=>getComputedStyle(document.documentElement).getAttribute? 'rgba(255,255,255,.05)':'rgba(255,255,255,.05)';
function gradient(ctx,a='rgba(184,255,68,.28)',b='rgba(184,255,68,0)'){const g=ctx.createLinearGradient(0,0,0,360);g.addColorStop(0,a);g.addColorStop(1,b);return g}
function lineChart(el,labels,values,opts={}){if(typeof el==='string')el=document.getElementById(el);if(!el||!window.Chart)return null;return new Chart(el,{type:'line',data:{labels,datasets:[{label:opts.label||'',data:values,borderColor:opts.color||'#B8FF44',backgroundColor:gradient(el.getContext('2d')),fill:true,tension:.42,pointRadius:0,pointHoverRadius:4,borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,animation:{duration:650},plugins:{legend:{display:false},tooltip:{mode:'index',intersect:false,callbacks:{label:c=>(opts.currency===false?'': '₹')+Number(c.raw).toLocaleString('en-IN')}}},scales:{x:{grid:{display:false},ticks:{color:chartText(),maxTicksLimit:8}},y:{grid:{color:'rgba(255,255,255,.05)'},ticks:{color:chartText(),callback:v=>(opts.currency===false?'':'₹')+Number(v).toLocaleString('en-IN')}}}}})}
function doughnutChart(el,labels,values){if(typeof el==='string')el=document.getElementById(el);if(!el||!window.Chart)return null;return new Chart(el,{type:'doughnut',data:{labels,datasets:[{data:values,backgroundColor:['#B8FF44','#44FFB2','#4FC3F7','#FFC857','#8C9EFF','#FF7AA2','#A78BFA'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'70%',plugins:{legend:{position:'bottom',labels:{color:chartText(),usePointStyle:true,padding:14}}}}})}
function barChart(el,labels,values,opts={}){if(typeof el==='string')el=document.getElementById(el);if(!el||!window.Chart)return null;return new Chart(el,{type:'bar',data:{labels,datasets:[{data:values,backgroundColor:values.map(v=>v>=0?'rgba(120,255,104,.75)':'rgba(255,94,108,.75)'),borderRadius:8}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{color:chartText()}},y:{grid:{color:'rgba(255,255,255,.05)'},ticks:{color:chartText(),callback:v=>v+'%'}}}}})}
function tinySpark(canvas,positive=true){if(!canvas||!window.Chart)return;const base=positive?50:70,vals=Array.from({length:12},(_,i)=>base+i*(positive?1.2:-.8)+(Math.random()*8-4));new Chart(canvas,{type:'line',data:{labels:vals.map((_,i)=>i),datasets:[{data:vals,borderColor:positive?'#78FF68':'#FF5E6C',borderWidth:1.5,pointRadius:0,tension:.4}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{enabled:false}},scales:{x:{display:false},y:{display:false}},animation:false}})}
